image: node:18

stages:
  - deploy

deploy_to_railway:
  stage: deploy
  script:
    - npm install -g @railway/cli
    - railway login --token $RAILWAY_TOKEN
    - railway up --yes
  only:
    - master
