version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  springboot:
    image: registry.gitlab.com/m3244263024/algorithmen:latest
    container_name: springboot
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data:
